#!/usr/bin/env python3
"""Generate Loon Host mappings from Repcz's flat Egern ChinaDomain rule set."""

import argparse
import hashlib
import json
import re
from pathlib import Path
from urllib.request import urlopen

SOURCE = "https://raw.githubusercontent.com/Repcz/Tool/X/Egern/Rules/ChinaDomain.yaml"
HERE = Path(__file__).resolve().parent
DOMESTIC_DNS = "223.5.5.5"
SYSTEM_DOMAINS = ("seu.edu.cn",)
DOMAIN_KEYS = ("domain_set", "domain_suffix_set", "domain_keyword_set")
IGNORED_KEYS = ("ip_cidr_set", "ip_cidr6_set", "user_agent_set")


def parse_rules(text):
    """Accept the upstream's flat YAML subset; fail on unrecognized syntax."""
    result = {}
    section = None
    for number, line in enumerate(text.splitlines(), 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if re.fullmatch(r"no_resolve: (true|false)", line):
            section = None
            continue
        match = re.fullmatch(r"([a-z_0-9]+):", line)
        if match:
            section = match[1]
            if section not in DOMAIN_KEYS + IGNORED_KEYS or section in result:
                raise ValueError(f"Line {number}: unknown or duplicate section {section}")
            result[section] = []
            continue
        if section is None or not line.startswith("  - "):
            raise ValueError(f"Line {number}: unsupported YAML syntax")
        value = line[4:].strip()
        if value.startswith("'"):
            if not value.endswith("'") or "'" in value[1:-1].replace("''", ""):
                raise ValueError(f"Line {number}: malformed single-quoted string")
            value = value[1:-1].replace("''", "'")
        elif value.startswith('"'):
            value = json.loads(value)
        if not isinstance(value, str) or not value or any(c.isspace() for c in value):
            raise ValueError(f"Line {number}: expected a nonempty scalar without whitespace")
        result[section].append(value)
    if not result.get("domain_suffix_set"):
        raise ValueError("Refusing to generate an empty domestic domain list")
    return result


def normalize_domain(value):
    value = value.rstrip(".").lower()
    if not value or any(c in value for c in "*?[]#=,:/\\"):
        raise ValueError(f"Invalid domain: {value!r}")
    encoded = value.encode("idna").decode("ascii")
    if len(encoded) > 253 or any(
        not re.fullmatch(r"[a-z0-9_](?:[a-z0-9_-]{0,61}[a-z0-9_])?", label)
        for label in encoded.split(".")
    ):
        raise ValueError(f"Invalid domain: {value!r}")
    return encoded


def build_mappings(rules):
    mappings = set()
    for domain in rules.get("domain_set", []):
        mappings.add(normalize_domain(domain))
    for domain in rules.get("domain_suffix_set", []):
        domain = normalize_domain(domain)
        # A suffix matches the apex and subdomains, but not 'notexample.com'.
        mappings.update((domain, "*." + domain))
    for keyword in rules.get("domain_keyword_set", []):
        if not re.fullmatch(r"[a-zA-Z0-9_.-]+", keyword):
            raise ValueError(f"Unsupported DNS keyword: {keyword!r}")
        mappings.add("*" + keyword.lower() + "*")
    return sorted(mappings)


def render(source):
    rules = parse_rules(source.decode("utf-8-sig"))
    mappings = build_mappings(rules)
    exceptions = [pattern for domain in SYSTEM_DOMAINS for pattern in (domain, "*." + domain)]
    mappings = [pattern for pattern in mappings if pattern not in exceptions]
    license_text = (HERE / "Repcz-LICENSE.txt").read_text(encoding="utf-8")
    header = [
        "#!name = ChinaDomain DNS Split",
        "#!desc = 国内名单使用 223.5.5.5；未命中使用主配置默认 DNS。请勿同时启用其他重叠的 DNS 映射插件。",
        "#!author = jiehu0; rules by Repcz",
        "#!homepage = https://github.com/jiehu0/Self_use_rule_materials/blob/main/loon/dns/README.md",
        "",
        "# Generated by loon/dns/generate.py; do not edit mappings manually.",
        f"# Source: {SOURCE}",
        f"# Source SHA-256: {hashlib.sha256(source).hexdigest()}",
        "# Domain source counts: " + ", ".join(f"{key}={len(rules.get(key, []))}" for key in DOMAIN_KEYS),
        "# Not applicable to DNS Host matching: " + ", ".join(f"{key}={len(rules.get(key, []))}" for key in IGNORED_KEYS),
        f"# Generated Host mappings: {len(mappings)} domestic + {len(exceptions)} campus exceptions",
        "# Does not replace global DNS, traffic rules, or node DNS settings.",
        "# Upstream rule data license:",
    ]
    header.extend("# " + line if line else "#" for line in license_text.splitlines())
    header.extend(("", "[Host]"))
    header.append("# Preserve campus DNS; list the specific exception before broad suffixes such as *.edu.cn.")
    header.extend(f"{pattern} = server:system" for pattern in exceptions)
    header.extend(f"{pattern} = server:{DOMESTIC_DNS}" for pattern in mappings)
    return "\n".join(header) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, help="Read a saved ChinaDomain.yaml instead of downloading")
    parser.add_argument("--output", type=Path, default=HERE.parent / "ChinaDomain_DNS.plugin")
    args = parser.parse_args()
    if args.source:
        source = args.source.read_bytes()
    else:
        with urlopen(SOURCE, timeout=30) as response:
            source = response.read()
    plugin = render(source)  # Validate everything before touching the existing file.
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temp = args.output.with_suffix(args.output.suffix + ".tmp")
    temp.write_text(plugin, encoding="utf-8")
    temp.replace(args.output)
    print(f"Generated {args.output}: {len(plugin.encode('utf-8')):,} bytes")


if __name__ == "__main__":
    main()
